// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9KXov2JuLLUQFZO45rhA7o4ivPce_zkY',
    appId: '1:822015454961:web:ea2f9df7ea8e56cc7a4350',
    messagingSenderId: '822015454961',
    projectId: 'women-safety-app-cd686',
    authDomain: 'women-safety-app-cd686.firebaseapp.com',
    storageBucket: 'women-safety-app-cd686.appspot.com',
    measurementId: 'G-6YRSN61MT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-TSFFLLoBMwEdf1K9EJElAJtoTj-Jzw',
    appId: '1:822015454961:android:90308b0646bc98577a4350',
    messagingSenderId: '822015454961',
    projectId: 'women-safety-app-cd686',
    storageBucket: 'women-safety-app-cd686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPGaa24JFwCXV3C6FZh0zd6wa6Y8Zm9c',
    appId: '1:822015454961:ios:eba8ae15b7eeda737a4350',
    messagingSenderId: '822015454961',
    projectId: 'women-safety-app-cd686',
    storageBucket: 'women-safety-app-cd686.appspot.com',
    androidClientId: '822015454961-v4tgn7t0krmknihrb3tebcr0ijklc6cq.apps.googleusercontent.com',
    iosClientId: '822015454961-4bv6vrakmbmg6ifrr4k0mc1n3218a35u.apps.googleusercontent.com',
    iosBundleId: 'com.example.women',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgPGaa24JFwCXV3C6FZh0zd6wa6Y8Zm9c',
    appId: '1:822015454961:ios:332a7e1aa44298ba7a4350',
    messagingSenderId: '822015454961',
    projectId: 'women-safety-app-cd686',
    storageBucket: 'women-safety-app-cd686.appspot.com',
    androidClientId: '822015454961-v4tgn7t0krmknihrb3tebcr0ijklc6cq.apps.googleusercontent.com',
    iosClientId: '822015454961-pj1kur90ou04ah8l6u9lah9bm9l350kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.women.RunnerTests',
  );
}
